"""Stores settings like learning rate, batch size, max episodes, save paths"""

TRACK_NAME = "corkscrew"

MAX_EPISODES = 300
MAX_STEPS = 3000
RELAUNCH_FREQUENCY = 25

LEARNING_RATE = 3e-4
GAMMA = 0.99
GAE_LAMBDA = 0.95
CLIP_EPSILON = 0.2

PPO_EPOCHS = 10
BATCH_SIZE = 64
UPDATE_TIMESTEPS = 514

MAX_STEER = 1.0
MAX_ACCEL = 1.0
MAX_BRAKE = 1.0

TRACK_SENSOR_COUNT = 19

STATE_DIM = 22
ACTION_DIM = 3

MODEL_SAVE_PATH = "../models/ppo/"
SAVE_INTERVAL = 50

LOG_PATH = "./logs/"
LOG_INTERVAL = 1

DEVICE = "cpu"

SPEED_WEIGHT = 1.0
ANGLE_PENALTY_WEIGHT = 50.0
TRACK_POSITION_WEIGHT = 20.0
DAMAGE_WEIGHT = 0.01
OFF_TRACK_PENALTY = 100.0

ACTION_STD_INIT = 0.6
MIN_ACTION_STD = 0.1
ACTION_STD_DECAY = 0.05
ACTION_STD_DECAY_FREQ = 250000